manageFiles/manageFiles/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""manageFiles URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from app import views
urlpatterns = [
	url(r'^register/$',views.register),								# 注册
	url(r'^$',views.index),											# 首页
	url(r'^api/files',views.api_files),								# 文件管理
	url(r'^api/users',views.api_register_user),					    # 注册请求
	url(r'^signin/$',views.signin),									# 登陆
    url(r'^signout/$',views.signout),                               # 注销
	url(r'^api/authenticate',views.api_authenticate),				# 登陆请求
	url(r'^api/fileupload/$',views.fileupload),					    # 文件上传
    url(r'^api/filedownload/$',views.file_download),                # 文件下载
    url(r'^api/searchfile',views.api_file_search),                  # 文件搜索
    url(r'^searchfile/',views.search_file),                         # 文件搜索
    url(r'^api/filedelete/$',views.file_delete),                    # 文件删除
    url(r'^checkForm/$',views.checkForm),                           # 审批团队表单
    url(r'^api/checkForm/$',views.api_checkForm),                   # 保存团队
    url(r'^signOff/$',views.sign_off_files),                        # 待签审文件列表
    url(r'^processForm/$',views.process_form),                      # 审批表单
    url(r'^api/process/$',views.api_process),                       # 获取流程节点
    url(r'^api/processForm/comments/$',views.api_create_comment),   # 审批意见/进入下一节点
    url(r'^api/backprocess/$',views.api_backprocess),               # 退回申请人


    url(r'^admin/', admin.site.urls),
]

manageFiles/app/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django import forms
from django.forms.extras.widgets import SelectDateWidget

department_choices =[('./upload/quality','品质部'),('./upload/technology','技术部')]
reason_choices =(('设计改进','设计改进'),('物料变换','物料变换'))

class Fileform(forms.Form):

    filename = forms.CharField(widget=forms.TextInput(attrs={'class': "uk-width-1-1",'placeholder':"上传附件后自动填写",'readonly':"readonly"}))
    filenumber = forms.CharField(widget=forms.TextInput(attrs={'class': "uk-width-1-1"}))
    department = forms.ChoiceField(widget=forms.Select(attrs={'class': "uk-width-1-1"}),choices=department_choices)
    caption = forms.CharField(widget=forms.TextInput(attrs={'class': "uk-width-1-1"}))
    reason = forms.ChoiceField(widget=forms.Select(attrs={'class': "uk-width-1-1"}),choices=reason_choices)
    department_down = forms.CharField(widget=forms.TextInput(attrs={'class': "uk-width-1-1"}))
    file_path = forms.FileField()

manageFiles/app/templates/__base__.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    {% block meta %}<!-- block meta  -->{% endblock %}
    <title>{% block title %} ? {% endblock %} - Manage Files</title>
    <link rel="stylesheet" href="/static/css/uikit.min.css">
    <link rel="stylesheet" href="/static/css/uikit.gradient.min.css">
    <link rel="stylesheet" href="/static/css/awesome.css" />
    <link rel="stylesheet" href="/static/css/search.css" />
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/sha1.min.js"></script>
    <script src="/static/js/uikit.js"></script>
    <script src="/static/js/sticky.min.js"></script>
    <script src="/static/js/vue.min.js"></script>
    <script src="/static/js/search.js"></script>  
    <script src="/static/js/awesome.js"></script>
    {% block beforehead %}<!-- before head  -->{% endblock %}
</head>
<body>
    <nav class="uk-navbar uk-navbar-attached uk-margin-bottom ">
        <div class="uk-container uk-container-center uk-tab">
            <a href="/" class="uk-navbar-brand uk-hidden-small">Manage Files</a>
            <a href="/"  class="uk-navbar-brand uk-hidden-large"><i class="uk-icon-home"></i></a>
            <ul class="uk-navbar-nav uk-hidden-small">
                <li data-url="blogs" class="uk-active"><a href="/"><i class="uk-icon-home"></i> 首页</a></li>
                <li><a href="/"  class="uk-navbar-brand uk-hidden-large"><i class="uk-icon-home"></i></a></li>
                <li><a target="_blank" href="https://github.com/mocangli/learngit"><i class="uk-icon-code"></i> 源码</a></li>  
            </ul>
            
            <div class="uk-navbar-content">
                <form id='searchForm' class="uk-form  uk-margin-remove uk-display-inline-block" action="/searchfile/" method="GET">
                    <input  name='filenum' type="text" placeholder="search" class="uk-form-small">
                    <button type=submit class="uk-button uk-button-primary uk-hidden-small"><i class="uk-icon-search"></i> 搜索</button>  
                    <button type=submit class="uk-button uk-button-primary uk-hidden-large"><i class="uk-icon-search"></i></button> 
                </form>
            </div>
            <div class="uk-hidden-small uk-navbar-flip">
                <ul class="uk-navbar-nav">
                {% if user %}
                    <li class="uk-parent" data-uk-dropdown>
                        <a href="#0"><i class="uk-icon-user"></i> {{ user.name }}</a>
                        <div class="uk-dropdown uk-dropdown-navbar">
                            <ul class="uk-nav uk-nav-navbar">
                                <li><a href="/signout"><i class="uk-icon-sign-out"></i> 登出</a></li>
                            </ul>
                        </div>
                    </li>
                {% else %}
                    <li>
                        <a href="/signin" class="uk-hidden-small"><i class="uk-icon-sign-in"></i> 登陆</a>
                        <a href="/signin" class="uk-visible-small"><i class="uk-icon-sign-in"></i></a>
                    </li>
                    <li>
                        <a href="/register" class="uk-hidden-small"><i class="uk-icon-edit"></i> 注册</a>
                        <a href="/register" class="uk-visible-small"><i class="uk-icon-edit"></i></a>
                    </li>
                {% endif %}
                </ul>
            </div>

            <div class='uk-navbar-nav uk-visible-small uk-navbar-flip'>
                <a href="#example" data-uk-offcanvas></a>
                <button class="uk-button" data-uk-offcanvas="{target:'#example'}">
                    <!-- 这是开关抽屉式边栏的按钮 --><i class="uk-icon-chevron-right"></i></button>
                <div id='example' class="uk-offcanvas">
                    <div class="uk-offcanvas-bar">
                        <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon">
                            <li><a target="_blank" href="https://github.com/mocangli/learngit"><i class="uk-icon-code"></i> 源码</a></li>

                        {% if user %}
                            <li class="uk-parent" data-uk-dropdown>
                                <a href="#0"><i class="uk-icon-user"></i> {{ user.name }}</a>
                                <div class="uk-dropdown uk-dropdown-navbar">
                                    <ul class="uk-nav uk-nav-navbar">
                                        <li><a href="/signout"><i class="uk-icon-sign-out"></i> 登出</a></li>
                                    </ul>
                                </div>
                            </li>
                        {% else %}
                            <li><a href="/signin"><i class="uk-icon-sign-in"></i> 登陆</a>   
                            </li>
                            <li><a href="/register"><i class="uk-icon-edit"></i> 注册</a>
                            </li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="uk-container uk-container-center">
        <div class="uk-grid">
            <!-- content -->
            {% block content %}
            {% endblock %}
            <!-- // content -->
        </div>
    </div>

    <div class="uk-margin-large-top" style="background-color:#eee; border-top:1px solid #ccc;">
        <div class="uk-container uk-container-center uk-text-center">
            <div class="uk-panel uk-margin-top uk-margin-bottom">
                <p>
                    <a target="_blank" href="http://weibo.com/liaoxuefeng" class="uk-icon-button uk-icon-weibo"></a>
                    <a target="_blank" href="https://github.com/mocangli" class="uk-icon-button uk-icon-github"></a>
                </p>
                <p>Powered by <a href="http://www.getuikit.net">uikit</a>. Copyright &copy; 2016.</p>
                <p><a href="http://www.liaoxuefeng.com/" target="_blank">www.liaoxuefeng.com</a>. All rights reserved.</p>
                <a target="_blank" href="http://www.w3.org/TR/html5/"><i class="uk-icon-html5" style="font-size:64px; color: #444;"></i></a>
            </div>

        </div>
    </div>
</body>
</html>

manageFiles/app/templates/checkForm.html
{% extends '__base__.html' %}

{% block title %}创建审批流程{% endblock %}

{% block beforehead %}
<script>
var file_id = '{{ id }}';

$(function () {
    var vm = new Vue({
        el: '#vm',
        data: {
            proofread: '',
            review: '',
            countersign: '',
            approved: '',
            Issued: ''           
        },
        methods: {
            submit: function (event) {
                event.preventDefault();
                var $form = $('#vm');
                if (! this.proofread.trim()) {
                    return $form.showFormError('请选择校对者');
                }
                if (! this.review.trim()) {
                    return $form.showFormError('请选择审核者');
                }
                if (! this.countersign.trim()) {
                    return $form.showFormError('请选择会签者');
                }
                if (! this.approved.trim()) {
                    return $form.showFormError('请选择批准者');
                }
                if (! this.Issued.trim()) {
                    return $form.showFormError('请选择下发者');
                }
                $form.postJSON('/api/checkForm/', {
                    proofread   : this.proofread.trim(),
                    review      : this.review.trim(),
                    countersign : this.countersign.trim(),
                    approved    : this.approved.trim(),
                    Issued      : this.Issued.trim(),
                    file_id     : file_id
                }, function (err, r) {
                    if (err) {
                        return $form.showFormError(err);
                    }
                    return location.assign('/');
                });
            }
        }
    });
    $('#vm').show();
});

</script>

{% endblock %}

{% block content %}

    <div class="uk-width-2-3">
        <h1>文件审批！</h1>
        <form id="vm" v-on="submit: submit" class="uk-form uk-form-stacked">
            <div class="uk-alert uk-alert-danger uk-hidden"></div>
            <div class="uk-form-row">
                <label class="uk-form-label">校对:</label>
                <div class="uk-form-controls">
                    <input v-model="proofread" type="text" maxlength="50" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">审核:</label>
                <div class="uk-form-controls">
                    <input v-model="review" type="text" maxlength="50" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">会签:</label>
                <div class="uk-form-controls">
                    <input v-model="countersign" type="text" maxlength="50" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">批准:</label>
                <div class="uk-form-controls">
                    <input v-model="approved" type="text" maxlength="50"  class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">下发:</label>
                <div class="uk-form-controls">
                    <input v-model="Issued" type="text" maxlength="50"  class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <button type="submit" class="uk-button uk-button-primary"><i class="uk-icon-save"></i> 审批</button>
                <a href="/" class="uk-button"><i class="uk-icon-times"></i> 取消</a>
            </div>
        </form>
    </div>

{% endblock %}

manageFiles/app/templates/index.html
{% extends '__base__.html' %}

{% block title %}首页{% endblock %}

{% block beforehead %}
<script>

Vue.filter('filter_time', function (value) {
    var d = Date.parse(value)
    var time = new Date(d)
 return time.toLocaleString();;
 })
function initVM(data) {
    $('#vm').show();
    var vm = new Vue({
        el: '#vm',
        data: {
            files: data.files,
            page: data.page
        },
        methods: {
            check_form: function (file) {
                location.assign('/checkForm/?id=' + file.pk);
            },
            delete_file: function (file) {
                if (confirm('确认要删除“' + file.fields.filename + '”？删除后不可恢复！')) {
                    postJSON('/api/filedelete/?id=' + file.pk, function (err, r) {
                        if (err) {
                            return alert(err.message || err.error || err);
                        }
                        refresh();
                    });
                }
            }
        }
    });  
    $('#vm').show();         
}

$(function() {
    getJSON('/api/files', {
        page: {{ page_index }}
    }, function (err, results) {
        if (err) {
            return fatal(err);
        }
        $('#loading').hide();
        initVM(results);
    });
});

</script>
{% endblock %}

{% block content %}

    <div class="uk-width-1-1 uk-margin-bottom">
        <div class="uk-panel uk-panel-box">
            <ul class="uk-breadcrumb">
                <li><a>搜索结果</a></li>
                <li><a href="/signOff/">到达的工作流</a></li>
                <li class="uk-active"><span>创建的工作流</span></li>
            </ul>
        </div>
    </div>

    <div id="error" class="uk-width-1-1">
    </div>

    <div id="loading" class="uk-width-1-1 uk-text-center">
        <span><i class="uk-icon-spinner uk-icon-medium uk-icon-spin"></i> 正在加载...</span>
    </div>

    <div id="vm" class="uk-width-1-1" style="display:none">
        <a href="/api/fileupload/" class="uk-button uk-button-primary"><i class="uk-icon-plus"></i> 上传文件</a>
        <table class="uk-table uk-table-hover">
            <thead>
                <tr>
                    <th class="uk-width-3-10">文件名</th>
                    <th class="uk-width-2-10">图号</th>
                    <th class="uk-width-3-10">创建时间</th>
                    <th class="uk-width-1-10">作者</th>
                    <th class="uk-width-1-10">操作</th>
                </tr>
            </thead>
            <tbody>
                <tr v-repeat="file: files" >
                    <td>
                        <a v-attr="href:'api/filedownload/?id='+file.pk" v-text="file.fields.filename"></a>
                    </td>
                    <td>
                        <a v-attr="href:'api/filedownload/?id='+file.pk" v-text="file.fields.filenumber"></a>
                    </td>
                    <td>
                        <span v-text="file.fields.created_at | filter_time"></span>
                    </td>
                    <td>
                        <span v-text="file.fields.user_name"></span>
                    </td>
                    <td><a href="#0" v-on="click: check_form(file)"><i class="uk-icon-edit"></i>
                        <a href="#0" v-on="click: delete_file(file)"><i class="uk-icon-trash-o"></i>
                    </td>
                </tr>
            </tbody>
        </table>
        <div v-component="pagination" v-with="page"></div>
    </div>
{% endblock %}

manageFiles/app/templates/process_form.html
{% extends '__base__.html' %}

{% block title %}签审流程{% endblock %}

{% block beforehead %}

<script>

$(function () {
    var ID = '{{ id }}',
        comment_url = '/api/processForm/comments/',
        back_url    =  '/api/backprocess/',
        radio1 = $('#form-s-r1'),
        radio2 = $('#form-s-r2'),
        $form = $('#form-comment');
    if (ID) {
        getJSON('/api/process/' , {
        id: ID
    }, function (err, form) {
            if (err) {
                return fatal(err);
            }
            $('#loading').hide();
            var ul1 = $('#reviewForm'),
                ul2 = $('#comment')
            var file_url = '/api/filedownload/?id='+form.files[0].pk;
            ul1.append('<li>校对：'+form.review.proofread_user+'</li>')
            ul1.append('<li>审核：'+form.review.review_user+'</li>')
            ul1.append('<li>会签：'+form.review.countersign_user+'</li>')
            ul1.append('<li>批准：'+form.review.approved_user+'</li>')
            ul1.append('<li>下发：'+form.review.Issued_user+'</li>')
            ul1.append("<li> 待审批文件：<a href=\'"+file_url+"\'>"+form.files[0].fields.filename +'</a></li>')
           for (var comment of form.comments) {
           ul2.append('<li>'+comment.fields.user_name+' : '+comment.fields.content+'</li>')
           }

        });
    }
    else {
        $('#loading').hide();
        initVM({
            proofread: '',
            review: '',
            countersign: '',
            approved: '',
            Issued: '' 
        });
    }
    $form.submit(function (e) {
            e.preventDefault();
            $form.showFormError('');
            var content = $form.find('textarea').val().trim();
//jQuery中判断radio是否选中
            if (content==='') {
                return $form.showFormError('请输审批意见！');
            }
            if (radio1.is(':checked')) {
                $form.postJSON(comment_url, { content: content,id: ID }, function (err, result) {
                if (err) {
                    return $form.showFormError(err);
                }
                alert('审批成功！');
                location.assign('/')
            });
            }
            if (radio2.is(':checked')) {
                $form.postJSON(back_url, { content: content,id: ID }, function (err, result) {
                if (err) {
                    return $form.showFormError(err);
                }
                alert('审批成功！');
                location.assign('/')
            });

            }
            
         })
});
</script>

{% endblock %}

{% block content %}
    <div id="error" class="uk-width-1-1">
    </div>

    <div id="loading" class="uk-width-1-1 uk-text-center">
        <span><i class="uk-icon-spinner uk-icon-medium uk-icon-spin"></i> 正在加载...</span>
    </div>

    <div  class="uk-width-medium-3-4">
        <ul id='reviewForm' class="uk-list uk-list-striped uk-list-space">

        </ul>


        <hr class="uk-article-divider">

        <h3>审核意见</h3>

        <article class="uk-comment">

            <div class="uk-comment-body">
                <form id="form-comment" class="uk-form">
                    <div class="uk-alert uk-alert-danger uk-hidden"></div>
                    <div class="uk-form-row">
                        <textarea rows="6" placeholder="说点什么吧" style="width:100%;resize:none;"></textarea>
                        <p><input id="form-s-r1" type="radio" checked="" name="radio2" value="1">
                        <label for="form-s-r1">进入下一节点</label>
                        <label><input id="form-s-r2" type="radio" name="radio2" value="2">退回</label></p>
                    </div>
                    <div class="uk-form-row"> 
                        <button type="submit" class="uk-button uk-button-primary"><i class="uk-icon-comment"></i> 提交</button>
                    </div>
                </form>
            </div>
        </article>

        <hr class="uk-article-divider">

                <h3>流程进度</h3>

        <ul id='comment' class="uk-list uk-list-striped uk-list-space">

        </ul>

{% endblock %}

manageFiles/app/templates/register.html
{% extends '__base__.html' %}

{% block title %}注册{% endblock %}

{% block beforehead %}

<script>

function validateEmail(email) {
    var re = /^[a-z0-9\.\-\_]+\@[a-z0-9\-\_]+(\.[a-z0-9\-\_]+){1,4}$/;
    return re.test(email.toLowerCase());
}

$(function () {
    var vm = new Vue({
        el: '#vm',
        data: {
            name: '',
            email: '',
            password1: '',
            password2: ''
        },
        methods: {
            submit: function (event) {
                event.preventDefault();
                var $form = $('#vm');
                if (! this.name.trim()) {
                    return $form.showFormError('请输入名字');
                }
                if (! validateEmail(this.email.trim().toLowerCase())) {
                    return $form.showFormError('请输入正确的Email地址');
                }
                if (this.password1.length < 6) {
                    return $form.showFormError('口令长度至少为6个字符');
                }
                if (this.password1 !== this.password2) {
                    return $form.showFormError('两次输入的口令不一致');
                }
                var email = this.email.trim().toLowerCase();
                $form.postJSON('/api/users', {
                    name: this.name.trim(),
                    email: email,
                    passwd: CryptoJS.SHA1(email + ':' + this.password1).toString()
                }, function (err, r) {
                    if (err) {
                        return $form.showFormError(err);
                    }
                    return location.assign('/');
                });
            }
        }
    });
    $('#vm').show();
});

</script>

{% endblock %}

{% block content %}

    <div class="uk-width-2-3">
        <h1>欢迎注册！</h1>
        <form id="vm" v-on="submit: submit" class="uk-form uk-form-stacked">
            <div class="uk-alert uk-alert-danger uk-hidden"></div>
            <div class="uk-form-row">
                <label class="uk-form-label">名字:</label>
                <div class="uk-form-controls">
                    <input v-model="name" type="text" maxlength="50" placeholder="名字" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">电子邮件:</label>
                <div class="uk-form-controls">
                    <input v-model="email" type="text" maxlength="50" placeholder="your-name@example.com" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">输入口令:</label>
                <div class="uk-form-controls">
                    <input v-model="password1" type="password" maxlength="50" placeholder="输入口令" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">重复口令:</label>
                <div class="uk-form-controls">
                    <input v-model="password2" type="password" maxlength="50" placeholder="重复口令" class="uk-width-1-1">
                </div>
            </div>
            <div class="uk-form-row">
                <button type="submit" class="uk-button uk-button-primary"><i class="uk-icon-user"></i> 注册</button>
            </div>
        </form>
    </div>

{% endblock %}

manageFiles/app/templates/search.html
{% extends '__base__.html' %}

{% block title %}搜索结果{% endblock %}

{% block beforehead %}
<script>

Vue.filter('filter_time', function (value) {
    var d = Date.parse(value)
    var time = new Date(d)
 return time.toLocaleString();;
 })
function initVM(data) {
    $('#vm').show();
    var vm = new Vue({
        el: '#vm',
        data: {
            files: data.files,
            page: data.page
        },
        methods: {
            check_form: function (file) {
                location.assign('/checkForm/?id=' + file.pk);
            },
            delete_file: function (file) {
                if (confirm('确认要删除“' + file.fields.filename + '”？删除后不可恢复！')) {
                    postJSON('/api/filedelete/?id=' + file.pk, function (err, r) {
                        if (err) {
                            return alert(err.message || err.error || err);
                        }
                        refresh();
                    });
                }
            }
        }
    });  
    $('#vm').show();         
}

$(function() {
    getJSON('/api/searchfile', {
        page: {{ page_index }},
        filenum: {{ filenum | safe}}
    }, function (err, results) {
        if (err) {
            return fatal(err);
        }
        $('#loading').hide();
        initVM(results);
    });
});


</script>
{% endblock %}

{% block content %}
    <div class="uk-width-1-1 uk-margin-bottom">
        <div class="uk-panel uk-panel-box">
            <ul class="uk-breadcrumb">
                <li class="uk-active"><span>搜索结果</span></li>
                <li><a href="/signOff/">到达的工作流</a></li>
                <li><a href="/">创建的工作流</a></li>
            </ul>
        </div>
    </div>

    <div id="error" class="uk-width-1-1">
    </div>

    <div id="loading" class="uk-width-1-1 uk-text-center">
        <span><i class="uk-icon-spinner uk-icon-medium uk-icon-spin"></i> 正在加载...</span>
    </div>

    <div id="vm" class="uk-width-1-1" style="display:none">
        <a href="/api/fileupload/" class="uk-button uk-button-primary"><i class="uk-icon-plus"></i> 上传文件</a>
        <table class="uk-table uk-table-hover">
            <thead>
                <tr>
                    <th class="uk-width-3-10">文件名</th>
                    <th class="uk-width-2-10">图号</th>
                    <th class="uk-width-3-10">创建时间</th>
                    <th class="uk-width-1-10">作者</th>
                    <th class="uk-width-1-10">操作</th>
                </tr>
            </thead>
            <tbody>
                <tr v-repeat="file: files" >
                    <td>
                        <a v-attr="href:'/api/filedownload/?id='+file.pk" v-text="file.fields.filename"></a>
                    </td>
                    <td>
                        <a v-attr="href:'/api/filedownload/?id='+file.pk" v-text="file.fields.filenumber"></a>
                    </td>
                    <td>
                        <span v-text="file.fields.created_at | filter_time"></span>
                    </td>
                    <td>
                        <span v-text="file.fields.user_name"></span>
                    </td>
                    <td><a href="#0" v-on="click: check_form(file)"><i class="uk-icon-edit"></i>
                        <a href="#0" v-on="click: delete_file(file)"><i class="uk-icon-trash-o"></i>
                    </td>
                </tr>
            </tbody>
        </table>
        <div v-component="pagination" v-with="page"></div>
    </div>
{% endblock %}

manageFiles/app/templates/upload.html
{% extends '__base__.html' %}

{% block title %}文件上传{% endblock %}

{% block beforehead %}
<script>
$(function () {
    var file=$('#id_file_path');
    file.change(function(){
        var filename = $('#id_filename');
        if (!file.val() || !(file.val().endsWith('.jpg') || file.val().endsWith('.png') || file.val().endsWith('.gif'))) {
    alert('Can only upload image file.');
    return false;
}
        getJSON('/api/searchfile', {
            filenum:'*'+file.val()+'*'
    }, function (err, results) {       
        if (results.files.length != 0) {
            alert('文件名已存在，请检查文件名后上传！'); 
            return           
        }
        filename.val(file.val());      
    });
    
        
    });

})
</script>
{% endblock %}

{% block content %}

    <div class="uk-width-2-3">
        <h1>请按要求填入以下信息！</h1>
        <form id='fileform' class="uk-form uk-form-stacked" enctype='multipart/form-data' method='POST'>
            <div class="uk-alert uk-alert-danger uk-hidden"></div>
            <div class="uk-form-row">
                <label class="uk-form-label">文件名:</label>
                <div class="uk-form-controls">
                    {{ form.filename }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">图号:</label>
                <div class="uk-form-controls">
                    {{ form.filenumber }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">部门:</label>
                <div class="uk-form-controls">
                    {{ form.department }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">说明:</label>
                <div class="uk-form-controls">
                    {{ form.caption }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">变更原因:</label>
                <div class="uk-form-controls">
                    {{ form.reason }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">下发单位:</label>
                <div class="uk-form-controls">
                    {{ form.department_down }}
                </div>
            </div>
            <div class="uk-form-row">
                <label class="uk-form-label">上传附件:</label>
                <div class="uk-form-controls">
                    {{ form.file_path }}
                </div>
            </div>
            <div class="uk-form-row">
                <button type="submit" class="uk-button uk-button-primary"><i class="uk-icon-user"></i> 提交</button>
            </div>
        </form>
    </div>

{% endblock %}